ServerEvents.recipes(event => {
    const COLOURS = [
        'white',
        'light_gray',
        'gray',
        'black',
        'brown',
        'red',
        'orange',
        'yellow',
        'lime',
        'green',
        'cyan',
        'light_blue',
        'blue',
        'purple',
        'magenta',
        'pink'
    ]
    const RECIPES = [
        'create:crafting/appliances/copper_backtank',
        'create:crafting/kinetics/wrench',
        'create:mechanical_crafting/wand_of_symmetry',
        'create:crafting/schematics/schematicannon',
        'create:crafting/schematics/schematic_table',
        'create:crafting/materials/andesite_alloy',
        'create:crafting/materials/andesite_alloy_from_zinc',
        'create:mixing/andesite_alloy',
        'create:mixing/andesite_alloy_from_zinc',
        'create:crafting/kinetics/shaft',
        'create:crafting/kinetics/cogwheel',
        'create:crafting/kinetics/large_cogwheel',
        'create:crafting/kinetics/large_cogwheel_from_little',
        'create:crafting/kinetics/encased_chain_drive',
        'create:crafting/kinetics/encased_chain_drive_from_zinc',
        'create:crafting/kinetics/belt_connector',
        'create:crafting/kinetics/nozzle',
        'create:crafting/kinetics/hand_crank',
        'create:crafting/kinetics/millstone',
        'create:crafting/kinetics/mechanical_press',
        'create:crafting/kinetics/empty_blaze_burner',
        'create:crafting/kinetics/depot',
        'create:crafting/kinetics/weighted_ejector',
        'create:crafting/kinetics/chute',
        'create:crafting/kinetics/smart_chute',
        'create:crafting/kinetics/wooden_bracket',
        'create:crafting/kinetics/metal_bracket',
        'create:crafting/kinetics/fluid_pipe_vertical',
        'create:crafting/kinetics/fluid_pipe',
        'create:crafting/kinetics/mechanical_pump',
        'create:crafting/kinetics/smart_fluid_pipe',
        'create:crafting/kinetics/fluid_valve',
        'create:crafting/kinetics/copper_valve_handle',
        'create:crafting/kinetics/fluid_tank',
        'create:crafting/kinetics/hose_pulley',
        'create:crafting/kinetics/item_drain',
        'create:crafting/kinetics/spout',
        'create:crafting/kinetics/steam_engine',
        'create:crafting/kinetics/steam_whistle',
        'create:crafting/kinetics/rope_pulley',
        'create:crafting/kinetics/elevator_pulley', // INTENTIONAL - MAKE ELEVATORS WITH SIMULATED
        'create:crafting/kinetics/cart_assembler',  // INTENTIONAL - COMMUNITY DECIDED THEY WERE TOO OP
        'create:crafting/kinetics/sticker',
        'create:crafting/kinetics/mechanical_drill',
        'create:crafting/kinetics/mechanical_saw',
        'create:crafting/logistics/redstone_contact',
        'create:crafting/kinetics/mechanical_harvester',
        'create:crafting/kinetics/mechanical_plough',
        'create:crafting/kinetics/white_sail',
        'create:crafting/kinetics/mechanical_crafter',
        'create:crafting/kinetics/mechanical_arm',
        'create:sequenced_assembly/track',
        'create:crafting/logistics/andesite_funnel',
        'create:crafting/logistics/andesite_tunnel',
        'create:crafting/logistics/brass_funnel',
        'create:crafting/logistics/brass_tunnel',
        'create:crafting/kinetics/item_vault',
        'create:crafting/logistics/item_hatch',
        'create:crafting/logistics/packager',
        'create:crafting/logistics/package_frogport',
        'create:crafting/logistics/redstone_requester',
        'create:crafting/kinetics/placard',
        'create:crafting/logistics/pulse_repeater',
        'create:crafting/logistics/pulse_extender',
        'create:crafting/logistics/pulse_timer',
        'create:crafting/curiosities/peculiar_bell',
        'create:haunting/haunted_bell',
        'create:crafting/logistics/desk_bell',
        'create:crafting/materials/rose_quartz',
        'create:crafting/kinetics/propeller',
        'create:crafting/kinetics/whisk',
        'create:crafting/kinetics/metal_girder',
        'create:crafting/kinetics/brass_hand',
        'create:crafting/materials/transmitter',
        'create:sequenced_assembly/precision_mechanism',
        'create:crushing/netherrack',
        'create:filling/sweet_roll',
        'create:mixing/honey',
        'create:emptying/honey_bottle',
        'create:filling/honeyed_apple',
        'create:crafting/materials/andesite_alloy_block',
        'create:crafting/materials/andesite_alloy_from_block',
        'create:crafting/materials/zinc_ingot_from_compacting',
        'create:crafting/materials/zinc_ingot_from_decompacting',
        'create:crafting/appliances/chain_from_zinc',
        'create:blasting/zinc_ingot_from_ore',
        'create:blasting/zinc_ingot_from_raw_ore',
        'create:blasting/zinc_ingot_from_crushed',
        'create:smelting/zinc_ingot_from_ore',
        'create:smelting/zinc_ingot_from_raw_ore',
        'create:smelting/zinc_ingot_from_crushed',
        'create:crafting/materials/zinc_block_from_compacting',
        'createaddition:pressing/zinc_ingot',
        'create:mixing/brass_ingot',
        'create:crafting/materials/brass_ingot_from_compacting',
        'create:crafting/materials/brass_ingot_from_decompacting',
        'create:crafting/materials/copper_ingot',
        'create:crafting/materials/brass_block_from_compacting',
        'createaddition:charging/electrify_gold_sheet',
        'createaddition:charging/electrify_gold_ingot',
        'createaddition:charging/electrify_gold_nugget',
        'createaddition:charging/electrify_gold_rod',
        'createaddition:charging/electrify_gold_block',
        'createaddition:charging/electrify_gold_wire',
        'create:crafting/kinetics/super_glue',
        'create:crafting/appliances/copper_diving_helmet',
        'create:crafting/appliances/copper_diving_boots',
        'create:crafting/materials/sand_paper',
        'create:crafting/materials/red_sand_paper',
        'createaddition:crushing/diamond',
        'createaddition:crafting/diamond_grit_sandpaper',
        'createaddition:crafting/electrum_ingot_from_electrum_block',
        'createaddition:crafting/electrum_block',
        'createaddition:mixing/electrum',
        'createaddition:rolling/copper_plate',
        'createaddition:rolling/gold_plate',
        'createaddition:rolling/iron_plate',
        'createaddition:rolling/electrum_plate',
        'createaddition:crafting/spool',
        'createaddition:crafting/copper_spool',
        'createaddition:crafting/gold_spool',
        'createaddition:crafting/electrum_spool',
        'createaddition:rolling/copper_ingot',
        'createaddition:rolling/iron_ingot',
        'createaddition:rolling/gold_ingot',
        'createaddition:rolling/brass_rod',
        'simulated:physics_assembler',
        'simulated:rope_winch',
        'simulated:rope_connector',
        'simulated:iron_handle',
        'simulated:red_portable_engine',
        'simulated:analog_transmission',
        'simulated:redstone_magnet',
        'simulated:spring',
        'simulated:rope_coupling',
        'simulated:sequenced_assembly/gyroscopic_mechanism',
        'simulated:sequenced_assembly/engine_assembly',
        'simulated:filling/honey_glue',
        'simulated:mechanical_crafting/plunger_launcher',
        'aeronautics:steam_vent',
        'aeronautics:mechanical_crafting/mounted_potato_cannon',
        'offroad:small_tire',
        'offroad:tire',
        'offroad:large_tire',
        'offroad:monstrous_tire',
        'create:copper_shingles_from_ingots_copper_stonecutting',
        'create:copper_tiles_from_ingots_copper_stonecutting',
        'create:pressing/copper_ingot',
        'create:pressing/gold_ingot',
        'create:pressing/brass_ingot',
        'create:pressing/iron_ingot',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ]
    RECIPES.forEach(removable => {
        event.remove(removable)
    })


    // --- SHEET REPLACEMENT LOGIC ---
    function replace(original, replacement)
    {
        event.replaceInput(
            {input:original, not:{output:'createaddition:alterntor'}}, // Alternators will use steel instead of wrought iron
            original,
            replacement
        )
        event.replaceOutput(
            {output:original},
            original,
            replacement
        )
    }
    replace('create:copper_sheet', 'tfc:metal/sheet/copper')
    replace('create:brass_sheet', 'tfc:metal/sheet/brass')
    replace('create:iron_sheet', 'tfc:metal/sheet/wrought_iron')
    replace('create:golden_sheet', 'tfc:metal/sheet/gold')
    replace('createaddition:zinc_sheet', 'tfc:metal/sheet/zinc')
    replace('minecraft:slime_ball', 'tfc:glue')

    // Postboxes, Shipping containers
    COLOURS.forEach(colour =>{
        event.remove('create:crafting/logistics/' + colour + '_postbox')
        event.remove('minecraft:' + colour + '_shipping_container')
    })
})